language: node_js
sudo: false
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - export CXX="g++-6"
install:
  - npm install
script: npm run test
